server:
  port: 8089

spring:
  application:
    name: GATEWAY

  cloud:
    gateway:
      routes:
        - id: PiMicro
          uri: lb://PIMICRO
          predicates:
            - Path=/stage-ing/**
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - AddResponseHeader=X-Response-Foo, Baz
      httpclient:
        multipart:
          max-in-memory-size: 10MB

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
